import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";
import MainContainer from "@/components/MainContainer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = typeof window === 'undefined' ? false : window?.location?.pathname?.startsWith('/login');
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-[var(--foreground)]`}>
        <div className="grid grid-cols-[240px_1fr] grid-rows-[64px_1fr] min-h-screen">
          <header className="col-span-2 h-16 glass flex items-center justify-between px-5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl" style={{background:"linear-gradient(135deg, var(--accent), var(--accent-2))"}} />
              <span className="font-semibold">Lucere Digital Media</span>
            </div>
            <nav className="text-sm flex items-center gap-4">
              <a href="https://github.com/merehb/website-playaround" className="hover:underline" target="_blank" rel="noreferrer">GitHub</a>
              <form action="/api/logout" method="post">
                <button className="btn btn-accent" formAction="/api/logout">Logout</button>
              </form>
            </nav>
          </header>
          <Sidebar />
          <MainContainer>{children}</MainContainer>
        </div>
      </body>
    </html>
  );
}

function NavLink({ href, label }: { href: string; label: string }) {
  return (
    <Link
      href={href}
      className="block px-3 py-2 rounded-xl hover:bg-white/5 transition-colors"
    >
      {label}
    </Link>
  );
}
