import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white text-gray-900`}>
        <div className="grid grid-cols-[220px_1fr] grid-rows-[56px_1fr] min-h-screen">
          <header className="col-span-2 h-14 border-b border-gray-200 flex items-center justify-between px-4">
            <div className="flex items-center gap-3">
              <Image src="/next.svg" alt="Lucere" width={24} height={24} className="dark:invert" />
              <span className="font-semibold">Lucere Digital Media</span>
            </div>
            <nav className="text-sm">
              <a href="https://github.com/merehb/website-playaround" className="hover:underline" target="_blank" rel="noreferrer">GitHub</a>
            </nav>
          </header>

          <aside className="row-span-1 row-start-2 border-r border-gray-200 p-3 space-y-1 bg-gray-50">
            <div className="text-xs font-semibold text-gray-600 px-2 py-1">Menu</div>
            <Link href="/" className="block px-2 py-2 rounded hover:bg-gray-100">Overview</Link>
            <Link href="/reporting" className="block px-2 py-2 rounded hover:bg-gray-100">Reporting & Insights</Link>
            <Link href="/planning" className="block px-2 py-2 rounded hover:bg-gray-100">Planning & Forecasting</Link>
            <Link href="/campaigns" className="block px-2 py-2 rounded hover:bg-gray-100">Campaigns</Link>
          </aside>

          <main className="p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
